# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '__register_ui__.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(760, 528)
        Register.setMinimumSize(QtCore.QSize(760, 528))
        Register.setMaximumSize(QtCore.QSize(760, 528))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/images/zong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Register.setWindowIcon(icon)
        Register.setStyleSheet("*{\n"
"font-size:24px;\n"
"font-family:sans-serif;\n"
"}\n"
"#Register{  \n"
"    border-image: url(:/pic/images/re.png)\n"
"\n"
"}\n"
"QFrame{\n"
"background:rgba(0,0,0,0.8);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton{\n"
"background:#03a9f4;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QLineEdit{\n"
"border-radius:15px;\n"
"color:#03a9f4;\n"
"}\n"
"QLabel{\n"
"color:#fff;\n"
"background:transparent;\n"
"font-size:30px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(Register)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 60, 591, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(230, 30, 221, 61))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 120, 141, 31))
        self.label.setStyleSheet("font: 16pt \"楷体\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 141, 31))
        self.label_3.setStyleSheet("font: 16pt \"楷体\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 141, 31))
        self.label_4.setStyleSheet("font: 16pt \"楷体\";")
        self.label_4.setObjectName("label_4")
        self.userId = QtWidgets.QLineEdit(self.frame)
        self.userId.setGeometry(QtCore.QRect(190, 110, 341, 41))
        self.userId.setStyleSheet("font: 14pt \"楷体\";")
        self.userId.setText("")
        self.userId.setObjectName("userId")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(190, 180, 341, 41))
        self.password.setStyleSheet("font: 14pt \"楷体\";")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.passwordAgain = QtWidgets.QLineEdit(self.frame)
        self.passwordAgain.setGeometry(QtCore.QRect(190, 250, 341, 41))
        self.passwordAgain.setStyleSheet("font: 14pt \"楷体\";")
        self.passwordAgain.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordAgain.setObjectName("passwordAgain")
        self.buttonRegister = QtWidgets.QPushButton(self.frame)
        self.buttonRegister.setGeometry(QtCore.QRect(50, 340, 151, 41))
        self.buttonRegister.setObjectName("buttonRegister")
        self.buttonCLear = QtWidgets.QPushButton(self.frame)
        self.buttonCLear.setGeometry(QtCore.QRect(220, 340, 151, 41))
        self.buttonCLear.setObjectName("buttonCLear")
        self.buttonExit = QtWidgets.QPushButton(self.frame)
        self.buttonExit.setGeometry(QtCore.QRect(390, 340, 151, 41))
        self.buttonExit.setObjectName("buttonExit")
        Register.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Register)
        self.statusbar.setObjectName("statusbar")
        Register.setStatusBar(self.statusbar)

        self.retranslateUi(Register)
        self.buttonExit.clicked.connect(Register.close)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register"))
        self.label_2.setText(_translate("Register", "注    册"))
        self.label.setText(_translate("Register", "用户名ID："))
        self.label_3.setText(_translate("Register", "密    码："))
        self.label_4.setText(_translate("Register", "重复密码："))
        self.userId.setPlaceholderText(_translate("Register", "空格不可用"))
        self.password.setPlaceholderText(_translate("Register", "请输入6到10位密码"))
        self.passwordAgain.setPlaceholderText(_translate("Register", "请再次输入密码"))
        self.buttonRegister.setText(_translate("Register", "注  册"))
        self.buttonCLear.setText(_translate("Register", "重  填"))
        self.buttonExit.setText(_translate("Register", "取  消"))
import myimages_rc
