# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\\ui\\login\\__ui__.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_systemClass(object):
    def setupUi(self, systemClass):
        systemClass.setObjectName("systemClass")
        systemClass.resize(940, 666)
        systemClass.setMinimumSize(QtCore.QSize(940, 666))
        systemClass.setMaximumSize(QtCore.QSize(940, 666))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/zong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        systemClass.setWindowIcon(icon)
        systemClass.setStyleSheet("*{\n"
"font-size:24px;\n"
"font-family:sans-serif;\n"
"}\n"
"#systemClass{  \n"
"background-image:\n"
"\n"
"}\n"
"QFrame{\n"
"background:rgba(0,0,0,0.8);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton{\n"
"background:#03a9f4;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QLineEdit{\n"
"border-radius:15px;\n"
"color:#03a9f4;\n"
"}\n"
"QLabel{\n"
"color:#fff;\n"
"background:transparent;\n"
"font-size:30px;\n"
"}\n"
"QTextEdit{\n"
"color:#fff;\n"
"background:transparent;\n"
"font-size:30px;\n"
"}\n"
"QCheckBox{\n"
"color:#fff;\n"
"background:transparent;\n"
"font-size:15px;\n"
"}")
        self.frame = QtWidgets.QFrame(systemClass)
        self.frame.setGeometry(QtCore.QRect(150, 110, 631, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonLogin = QtWidgets.QPushButton(self.frame)
        self.buttonLogin.setGeometry(QtCore.QRect(80, 320, 201, 41))
        self.buttonLogin.setObjectName("buttonLogin")
        self.user = QtWidgets.QLineEdit(self.frame)
        self.user.setGeometry(QtCore.QRect(80, 90, 461, 51))
        self.user.setText("")
        self.user.setCursorPosition(0)
        self.user.setObjectName("user")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(80, 180, 461, 51))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setCursorPosition(0)
        self.password.setObjectName("password")
        self.checkRemember = QtWidgets.QCheckBox(self.frame)
        self.checkRemember.setGeometry(QtCore.QRect(80, 260, 151, 41))
        self.checkRemember.setObjectName("checkRemember")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 81, 71))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.buttonForget = QtWidgets.QTextEdit(self.frame)
        self.buttonForget.setGeometry(QtCore.QRect(430, 260, 104, 31))
        self.buttonForget.setObjectName("buttonForget")
        self.buttonRegister = QtWidgets.QPushButton(self.frame)
        self.buttonRegister.setGeometry(QtCore.QRect(340, 320, 201, 41))
        self.buttonRegister.setObjectName("buttonRegister")
        self.label = QtWidgets.QLabel(systemClass)
        self.label.setGeometry(QtCore.QRect(40, 40, 851, 571))
        self.label.setStyleSheet("border-image:url(:/images/tu01.png)\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.closeButton = QtWidgets.QPushButton(systemClass)
        self.closeButton.setGeometry(QtCore.QRect(820, 60, 50, 28))
        self.closeButton.setMinimumSize(QtCore.QSize(50, 28))
        self.closeButton.setMaximumSize(QtCore.QSize(50, 28))
        self.closeButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.closeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setObjectName("closeButton")
        self.minButton = QtWidgets.QPushButton(systemClass)
        self.minButton.setGeometry(QtCore.QRect(770, 60, 50, 28))
        self.minButton.setMinimumSize(QtCore.QSize(50, 28))
        self.minButton.setMaximumSize(QtCore.QSize(50, 28))
        self.minButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.minButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/images/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon2)
        self.minButton.setObjectName("minButton")
        self.label_3 = QtWidgets.QLabel(systemClass)
        self.label_3.setGeometry(QtCore.QRect(60, 50, 61, 41))
        self.label_3.setStyleSheet("image: url(:/pic/images/zong.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(systemClass)
        self.label_4.setGeometry(QtCore.QRect(120, 60, 309, 31))
        self.label_4.setObjectName("label_4")
        self.label.raise_()
        self.frame.raise_()
        self.closeButton.raise_()
        self.minButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()

        self.retranslateUi(systemClass)
        self.closeButton.clicked.connect(systemClass.close)
        self.minButton.clicked.connect(systemClass.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(systemClass)

    def retranslateUi(self, systemClass):
        _translate = QtCore.QCoreApplication.translate
        systemClass.setWindowTitle(_translate("systemClass", "system"))
        self.buttonLogin.setText(_translate("systemClass", "登    录"))
        self.user.setPlaceholderText(_translate("systemClass", " 用户名"))
        self.password.setPlaceholderText(_translate("systemClass", " 密码"))
        self.checkRemember.setText(_translate("systemClass", "记住密码"))
        self.label_2.setText(_translate("systemClass", "Login"))
        self.buttonForget.setHtml(_translate("systemClass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'sans-serif\'; font-size:30px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:15px; text-decoration: underline; color:#00aaff;\">忘记密码？</span></p></body></html>"))
        self.buttonRegister.setText(_translate("systemClass", "注    册"))
        self.label_4.setText(_translate("systemClass", "<html><head/><body><p><span style=\" font-size:12pt;\">行人检测与追踪系统</span></p></body></html>"))
